version: "3"

services:
  ###############################################################
  #                Our core monitoring stack                    #
  ###############################################################
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090 # Prometheus listens on port 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # We mount a custom prometheus config
        # file to scrap cAdvisor and HAProxy
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  grafana: # Garafana needs no config file since
    image: grafana/grafana # we configure it once it's up
    ports:
      - 3000:3000 # Grafana listens on port 3000
    depends_on: [prometheus]

  ###############################################################
  #            Agent to collect runtime metrics                 #
  ###############################################################
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes: # Don't ask me why I mounted all these
      - /:/rootfs:ro # directories. I simply copied these
      - /var/run:/var/run:rw # mounts from the documentation.
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  ###############################################################
  #                          HA proxy                           #
  ###############################################################
  haproxy: # We are using HAProxy as our reverse
    image: haproxy:2.3 # proxy here
    ports:
      - 11000:11000 # I've configured HAProxy to run on 11000
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg # We mount a custom config file to proxy
    deploy: # between both the services
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    depends_on: [svc-greeter, svc-math]

  haproxy-exporter:
    image: prom/haproxy-exporter # Need to point the exporter to haproxy
    command: '--haproxy.scrape-uri="http://haproxy:8404/stats;csv"'
    depends_on: [haproxy]

  ###############################################################
  #                       Our Microservices                     #
  ###############################################################
  svc-greeter: # These are our services. Nothing fancy
    image: spaceuptech/greeter
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 512M

  svc-math:
    image: spaceuptech/basic-service
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 512M
